name: Renovate
on: [pull_request]
  # schedule:
  #   # The "*" (#42, asterisk) character has special semantics in YAML, so this
  #   # string has to be quoted.
  #   - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v21.29.2
        with:
          configurationFile: renovate-action-config.js
          token: ${{ secrets.GH_ACCESS_TOKEN }}
        env:
          RENOVATE_HOST_RULES: '[{"hostName":"app.terraform.io","token":${{ secrets.TF_ACCESS_TOKEN }}}]'